/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab8p2_diegocruz;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dfcm9
 */
public class MainFrame extends javax.swing.JFrame {
    
    ArrayList <Pais> paises = new ArrayList();
    ArrayList <Nadador> nadgenerales = new ArrayList();
    ArrayList <Evento> eventos = new ArrayList();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        llenarnads();
        llenareven();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm_tblnad = new javax.swing.JPopupMenu();
        pm_tbleven = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        tp_menu = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        tf_nompais = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        js_medallaspais = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jb_addpais = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_nombrenad = new javax.swing.JTextField();
        tf_estaturanad = new javax.swing.JTextField();
        tf_tiemponad = new javax.swing.JTextField();
        js_edadnad = new javax.swing.JSpinner();
        cb_paisnad = new javax.swing.JComboBox<>();
        cb_distancianad = new javax.swing.JComboBox<>();
        js_medallasnad = new javax.swing.JSpinner();
        cb_estilonad = new javax.swing.JComboBox<>();
        jb_addnadador = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cb_estiloeven = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cb_distanciaeven = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_recordevent = new javax.swing.JTextField();
        jb_addevent = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_nads = new javax.swing.JTable();
        cb_paislistnad = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_eventos = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cb_nad1 = new javax.swing.JComboBox<>();
        cb_nad2 = new javax.swing.JComboBox<>();
        cb_nad3 = new javax.swing.JComboBox<>();
        jpb_nad1 = new javax.swing.JProgressBar();
        jpb_nad2 = new javax.swing.JProgressBar();
        jpb_nad3 = new javax.swing.JProgressBar();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cb_eventosim = new javax.swing.JComboBox<>();
        jb_sim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        tp_menu.setBackground(new java.awt.Color(0, 102, 204));
        tp_menu.setForeground(new java.awt.Color(0, 0, 0));
        tp_menu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_menuStateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese Nombre:");

        js_medallaspais.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese Medallas:");

        jb_addpais.setBackground(new java.awt.Color(0, 102, 204));
        jb_addpais.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jb_addpais.setForeground(new java.awt.Color(255, 255, 255));
        jb_addpais.setText("Agregar");
        jb_addpais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addpaisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nompais, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_medallaspais, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jb_addpais, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(js_medallaspais, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(tf_nompais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(jb_addpais, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        tp_menu.addTab("Agregar Pais", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad");

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estatura");

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nacionalidad");

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tiempo mas rapido:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Numero de Medallas");

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estilo:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Distancia (mts):");

        tf_nombrenad.setText("\n");

        tf_estaturanad.setText("\n");

        tf_tiemponad.setText("\n");

        cb_distancianad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800" }));

        cb_estilonad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa", " " }));

        jb_addnadador.setBackground(new java.awt.Color(0, 102, 204));
        jb_addnadador.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jb_addnadador.setForeground(new java.awt.Color(255, 255, 255));
        jb_addnadador.setText("Agregar");
        jb_addnadador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addnadadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_paisnad, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombrenad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_edadnad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_estaturanad, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_estilonad, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_medallasnad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_distancianad, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tiemponad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jb_addnadador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombrenad, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(cb_distancianad))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_tiemponad, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(cb_paisnad))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_edadnad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_medallasnad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_estaturanad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_estilonad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_addnadador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        tp_menu.addTab("Agregar Nadador", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        cb_estiloeven.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa", " " }));

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Distancia (mts):");

        cb_distanciaeven.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Record Actual:");

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Estilo:");

        jb_addevent.setBackground(new java.awt.Color(0, 102, 204));
        jb_addevent.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jb_addevent.setForeground(new java.awt.Color(255, 255, 255));
        jb_addevent.setText("Agregar");
        jb_addevent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addeventMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_recordevent)
                    .addComponent(cb_estiloeven, 0, 214, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_distanciaeven, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_addevent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_distanciaeven, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_estiloeven, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_recordevent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jb_addevent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        tp_menu.addTab("Agregar Evento", jPanel4);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        jt_nads.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_nads);

        cb_paislistnad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_paislistnadItemStateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Seleccione Pais:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_paislistnad, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_paislistnad, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        tp_menu.addTab("Listar Nadadores", jPanel5);

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));

        jt_eventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jt_eventos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        tp_menu.addTab("Listar Eventos", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        tp_menu.addTab("Listar Ganadores", jPanel7);

        jPanel8.setBackground(new java.awt.Color(153, 0, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Escoger Nadador 2:");

        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Escoger Nadador 1:");

        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Escoger Nadador 3:");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nadador 1:");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nadador 2:");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nadador 3:");

        jLabel22.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Escoger Evento:");

        cb_eventosim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_eventosimItemStateChanged(evt);
            }
        });

        jb_sim.setBackground(new java.awt.Color(255, 0, 153));
        jb_sim.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jb_sim.setForeground(new java.awt.Color(255, 255, 255));
        jb_sim.setText("Simular");
        jb_sim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_simMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(cb_nad1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(cb_nad2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_eventosim, 0, 155, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(95, 95, 95)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb_nad3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jb_sim, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jpb_nad3, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpb_nad2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpb_nad1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 94, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_nad3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_eventosim, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jb_sim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_nad2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_nad1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpb_nad1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jpb_nad2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpb_nad3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        tp_menu.addTab("Simulacion", jPanel8);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lab de Juegos Olimpicos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tp_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(tp_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_addpaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addpaisMouseClicked
        
        
        try {
            String nom;
            int med;
            nom = tf_nompais.getText();
            med = (int) js_medallaspais.getValue();
            Pais nuevo = new Pais(nom,med);
            paises.add(nuevo);
            
            AdminPais adpais = new AdminPais("./Paises.dcmf");
            adpais.cargarArchivo();
            adpais.setPais(nuevo);
            adpais.escribirArchivo();
            
            
            JOptionPane.showMessageDialog(null, "El pais se ha agregado exitosamente!");
            tf_nompais.setText("");
            js_medallaspais.setValue(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jb_addpaisMouseClicked

    private void jb_addnadadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addnadadorMouseClicked
        try {
            llenarpaises();
            llenarnads();
            String nom, est;
            int edad, dist, med;
            double height, tiem;
            Pais paisnad = (Pais) cb_paisnad.getSelectedItem();
            nom = tf_nombrenad.getText();
            edad = (int) js_edadnad.getValue();
            est = cb_estilonad.getSelectedItem().toString();
            int cont = 0;
            for (Nadador nadadore : paises.get(cb_paisnad.getSelectedIndex()).getNadadores()) {
                if(nadadore.getEstilo().equals(est)){
                    cont++;
                }
                
            }
            if(cont<2){
                
            
                dist = Integer.parseInt(cb_distancianad.getSelectedItem().toString());
                med = (int) js_medallasnad.getValue();
                height = Double.parseDouble(tf_estaturanad.getText());
                tiem = Double.parseDouble(tf_tiemponad.getText());

                Nadador nuevonad = new Nadador(nom, paisnad, edad, height, tiem, est, dist, med);
                for (Pais nac : paises) {
                    if (nac.getNombre().equals(paisnad.getNombre())){
                        nac.getNadadores().add(nuevonad);

                    }
                }

                AdminPais adpais = new AdminPais("./Paises.dcmf");
                adpais.cargarArchivo();
                adpais.setPaises(new ArrayList());
                for (Pais paise : paises) {
                    adpais.setPais(paise);
                }
                adpais.escribirArchivo();


                nadgenerales.add(nuevonad);

                AdminNadador an= new AdminNadador("./nadadores.dcmf");
                an.cargarArchivo();
                an.setNadador(nuevonad);
                an.escribirArchivo();

                JOptionPane.showMessageDialog(null, "El nadador ha sido agregado exitosamente!");
            
            }
            tf_estaturanad.setText("");
            tf_nombrenad.setText("");
            tf_tiemponad.setText("");
            js_edadnad.setValue(0);
            js_medallasnad.setValue(0);
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_addnadadorMouseClicked

    private void tp_menuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_menuStateChanged
        if (tp_menu.getSelectedIndex() == 1){
            llenarpaises();
            if (paises.isEmpty()){
                jb_addnadador.setEnabled(false);
            }
            else{
                jb_addnadador.setEnabled(true);
                DefaultComboBoxModel modelo = new DefaultComboBoxModel();
                modelo.addAll(paises);
                cb_paisnad.setModel(modelo);
            }
            
            
        }
        if(tp_menu.getSelectedIndex()==3){
            jt_nads.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Nombre", "Edad", "Estatura", "Tiempo", "Estilo", "Distancia", "Medallas"
                        }
                        ));
            llenarpaises();
            if (paises.isEmpty()){
                jb_addnadador.setEnabled(false);
            }
            else{
                jb_addnadador.setEnabled(true);
                DefaultComboBoxModel modelo = new DefaultComboBoxModel();
                modelo.addAll(paises);
                cb_paislistnad.setModel(modelo);
            }
            
        }
        if (tp_menu.getSelectedIndex()==4){
            jt_eventos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Estilo", "Distancia", "Record"
                        }
            ));
            for (Evento evento : eventos) {
                Object [] row = {evento.getEstilo(),evento.getDistancia(),evento.getRecord()};
                DefaultTableModel modelo = (DefaultTableModel) jt_eventos.getModel();
                modelo.addRow(row);
                jt_eventos.setModel(modelo);
            }
        }
        if (tp_menu.getSelectedIndex()==6){
            llenarnads();
            llenareven();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            modelo.addAll(eventos);
            cb_eventosim.setModel(modelo);
                
            
        }
    }//GEN-LAST:event_tp_menuStateChanged

    private void jb_addeventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addeventMouseClicked
        try {
            String est;
            int dist;
            double rec;

            est = cb_estiloeven.getSelectedItem().toString();
            dist = Integer.parseInt(cb_distanciaeven.getSelectedItem().toString());
            rec = Double.parseDouble(tf_recordevent.getText());

            Evento neweven = new Evento(est, dist, rec);
            eventos.add(neweven);

            AdminEvento ae = new AdminEvento("./eventos.dcmf");
            ae.cargarArchivo();
            ae.setEvento(neweven);
            ae.escribirArchivo();
            
            JOptionPane.showMessageDialog(this, "El evento ha sido agregado exitosamente!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
            e.printStackTrace();
        }
        
        
        
        
    }//GEN-LAST:event_jb_addeventMouseClicked

    private void cb_paislistnadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_paislistnadItemStateChanged
        try {
                if(evt.getStateChange() ==1){
                    Pais temp = (Pais) cb_paislistnad.getSelectedItem();
                    if(cb_paislistnad.getSelectedItem()!= null){
                        ArrayList<Nadador> temp2 = temp.getNadadores();
                        jt_nads.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Nombre", "Edad", "Estatura", "Tiempo", "Estilo", "Distancia", "Medallas"
                        }
                        ));
                        
                        for (Nadador nadador : temp2) {
                            Object [] row = {nadador.getNombre(),nadador.getEdad(),nadador.getEstatura(),nadador.getTiempo(),nadador.getEstilo(),nadador.getDistancia(),nadador.getMedallas()};
                            DefaultTableModel modelo = (DefaultTableModel) jt_nads.getModel();
                            modelo.addRow(row);
                            jt_nads.setModel(modelo);
                            
                        }

                    }
                    
                }
                
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocurrio un error");
                e.printStackTrace();
            }
    }//GEN-LAST:event_cb_paislistnadItemStateChanged

    private void cb_eventosimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_eventosimItemStateChanged
        try {
            llenarnads();
            
            if (evt.getStateChange() ==1){
                DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
                DefaultComboBoxModel modelo3 = new DefaultComboBoxModel();
                DefaultComboBoxModel modelo4 = new DefaultComboBoxModel();
                for (Nadador ndgn : nadgenerales) {
                    if( ( ((Evento)cb_eventosim.getSelectedItem()).getDistancia()==ndgn.getDistancia() ) && ((Evento) cb_eventosim.getSelectedItem()).getEstilo().equals(ndgn.getEstilo())){
                        modelo2.addElement(ndgn);
                        modelo3.addElement(ndgn);
                        modelo4.addElement(ndgn);
                    }
                    
                }
                cb_nad1.setModel(modelo2);
                cb_nad2.setModel(modelo3);
                cb_nad3.setModel(modelo4);

            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_cb_eventosimItemStateChanged

    private void jb_simMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_simMouseClicked
        try {
            int hay = 0;
            Evento tem = (Evento) cb_eventosim.getSelectedItem();
            if (cb_nad1.getSelectedItem()!=null){
                hay++;
            }
            if (cb_nad2.getSelectedItem()!=null){
               hay++;
            }
            if (cb_nad3.getSelectedItem()!=null){
                hay++;
            }
            if (cb_eventosim.getSelectedItem()!= null && hay >=2) {
                ThrSim trnad1 = new ThrSim(jpb_nad1);
                ThrSim trnad2 = new ThrSim(jpb_nad2);
                ThrSim trnad3 = new ThrSim(jpb_nad3);
                Thrchecker acabar = new Thrchecker(jpb_nad1, jpb_nad2, jpb_nad3);
                acabar.start();
                if (cb_nad1.getSelectedItem() != null){
                    trnad1.start();
                }
                if (cb_nad1.getSelectedItem() != null){
                    trnad2.start();
                }
                if (cb_nad1.getSelectedItem() != null){
                    trnad3.start();
                }
                
                boolean cont = true;
                while (cont){
                    if (acabar.isAcabo()){
                        cont = false;
                        trnad1.setVida(false);
                        trnad2.setVida(false);
                        trnad3.setVida(false);
                        
                    }
                }
                
                
                int valor = Math.max(jpb_nad1.getValue(), jpb_nad2.getValue());
                valor = Math.max(valor, jpb_nad2.getValue());
                if (valor == jpb_nad1.getValue()){
                    JOptionPane.showMessageDialog(this, "Evento:\nEstilo: "+((Evento)cb_eventosim.getSelectedItem()).getEstilo()+
                            "\nDistancia"+((Evento)cb_eventosim.getSelectedItem()).getDistancia()+"\nRecord: "+((Evento)cb_eventosim.getSelectedItem()).getRecord()
                            +"\nGanador:"+cb_nad1.getSelectedItem().toString());
                }
                else if (valor == jpb_nad2.getValue()){
                    JOptionPane.showMessageDialog(this, "Evento:\nEstilo: "+((Evento)cb_eventosim.getSelectedItem()).getEstilo()+
                            "\nDistancia"+((Evento)cb_eventosim.getSelectedItem()).getDistancia()+"\nRecord: "+((Evento)cb_eventosim.getSelectedItem()).getRecord()
                            +"\nGanador:"+cb_nad2.getSelectedItem().toString());
                }
                else if (valor == jpb_nad3.getValue()){
                    JOptionPane.showMessageDialog(this, "Evento:\nEstilo: "+((Evento)cb_eventosim.getSelectedItem()).getEstilo()+
                            "\nDistancia"+((Evento)cb_eventosim.getSelectedItem()).getDistancia()+"\nRecord: "+((Evento)cb_eventosim.getSelectedItem()).getRecord()
                            +"\nGanador:"+cb_nad3.getSelectedItem().toString());
                    
                }
               
                
            }
            
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_simMouseClicked

    private void llenarpaises(){
        paises.clear();
        AdminPais pai = new AdminPais("./Paises.dcmf");
        pai.cargarArchivo();
        paises.addAll(pai.getPaises());
        
    }
    
    private void llenarnads(){
        nadgenerales.clear();
        AdminNadador adna = new AdminNadador("./nadadores.dcmf");
        adna.cargarArchivo();
        nadgenerales.addAll(adna.getNadadores());
    }
    
    private void llenareven(){
        eventos.clear();
        AdminEvento adev = new AdminEvento("./eventos.dcmf");
        adev.cargarArchivo();
        eventos.addAll(adev.getEventos());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_distanciaeven;
    private javax.swing.JComboBox<String> cb_distancianad;
    private javax.swing.JComboBox<String> cb_estiloeven;
    private javax.swing.JComboBox<String> cb_estilonad;
    private javax.swing.JComboBox<String> cb_eventosim;
    private javax.swing.JComboBox<String> cb_nad1;
    private javax.swing.JComboBox<String> cb_nad2;
    private javax.swing.JComboBox<String> cb_nad3;
    private javax.swing.JComboBox<String> cb_paislistnad;
    private javax.swing.JComboBox<String> cb_paisnad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_addevent;
    private javax.swing.JButton jb_addnadador;
    private javax.swing.JButton jb_addpais;
    private javax.swing.JButton jb_sim;
    private javax.swing.JProgressBar jpb_nad1;
    private javax.swing.JProgressBar jpb_nad2;
    private javax.swing.JProgressBar jpb_nad3;
    private javax.swing.JSpinner js_edadnad;
    private javax.swing.JSpinner js_medallasnad;
    private javax.swing.JSpinner js_medallaspais;
    private javax.swing.JTable jt_eventos;
    private javax.swing.JTable jt_nads;
    private javax.swing.JPopupMenu pm_tbleven;
    private javax.swing.JPopupMenu pm_tblnad;
    private javax.swing.JTextField tf_estaturanad;
    private javax.swing.JTextField tf_nombrenad;
    private javax.swing.JTextField tf_nompais;
    private javax.swing.JTextField tf_recordevent;
    private javax.swing.JTextField tf_tiemponad;
    private javax.swing.JTabbedPane tp_menu;
    // End of variables declaration//GEN-END:variables
}
